service: recaptcha-test
org: domengabrovsek
app: recaptcha-test
console: true
# https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
variablesResolutionMode: 20210326

# throw error before trying to deploy if something is wrong in config
configValidationMode: error

# create an optimized package for our functions
package:
  individually: true

provider:
  # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: eu-central-1
  environment:
    RECAPTCHA_SITE_KEY: ${ssm:/recaptcha-site-key}
functions:
  recaptcha:
    handler: lambda.handler
    events:
      - http:
          method: get
          path: recaptcha
          cors: true